/**
 *  @reference https://github.com/vaalentin/keycodes
 */

export const GamepadEvents = [
	"GAMEPAD_LSTICK_NORTH",
	"GAMEPAD_LSTICK_SOUTH",
	"GAMEPAD_LSTICK_EAST",
	"GAMEPAD_LSTICK_WEST",
	"GAMEPAD_LSTICK_PRESS",

	"GAMEPAD_RSTICK_NORTH",
	"GAMEPAD_RSTICK_SOUTH",
	"GAMEPAD_RSTICK_EAST",
	"GAMEPAD_RSTICK_WEST",
	"GAMEPAD_RSTICK_PRESS",

	"GAMEPAD_DPAD_NORTH",
	"GAMEPAD_DPAD_SOUTH",
	"GAMEPAD_DPAD_EAST",
	"GAMEPAD_DPAD_WEST",

	"GAMEPAD_RTRIGGER_TOP",
	"GAMEPAD_RTRIGGER_BOTTOM",

	"GAMEPAD_LTRIGGER_TOP",
	"GAMEPAD_LTRIGGER_BOTTOM",

	"GAMEPAD_BUTTON_NORTH",
	"GAMEPAD_BUTTON_SOUTH",
	"GAMEPAD_BUTTON_EAST",
	"GAMEPAD_BUTTON_WEST",

	"GAMEPAD_BUTTON_START",
	"GAMEPAD_BUTTON_SELECT",
]

export const GamepadButtons = {
	0: "GAMEPAD_BUTTON_SOUTH",
	1: "GAMEPAD_BUTTON_EAST",
	2: "GAMEPAD_BUTTON_WEST",
	3: "GAMEPAD_BUTTON_NORTH",
	4: "GAMEPAD_RTRIGGER_TOP",
	5: "GAMEPAD_LTRIGGER_TOP",
	6: "GAMEPAD_RTRIGGER_BOTTOM",
	7: "GAMEPAD_LTRIGGER_BOTTOM",
	8: "GAMEPAD_BUTTON_SELECT",
	9: "GAMEPAD_BUTTON_START",
	10: "GAMEPAD_LSTICK_PRESS",
	11: "GAMEPAD_RSTICK_PRESS",
	12: "GAMEPAD_DPAD_NORTH",
	13: "GAMEPAD_DPAD_SOUTH",
	14: "GAMEPAD_DPAD_EAST",
	15: "GAMEPAD_DPAD_WEST",
}

export const GamepadAxes = {
	0: [ "GAMEPAD_LSTICK_WEST", "GAMEPAD_LSTICK_EAST" ],
	1: [ "GAMEPAD_LSTICK_SOUTH", "GAMEPAD_LSTICK_NORTH" ],
	2: [ "GAMEPAD_RSTICK_WEST", "GAMEPAD_RSTICK_EAST" ],
	3: [ "GAMEPAD_RSTICK_SOUTH", "GAMEPAD_RSTICK_NORTH" ],
}
